kind: project
metadata:
  name: new-git-proj
  created: '2023-04-02T14:00:12.006000'
spec:
  functions:
  - url: ./src/data_fetch.py
    name: data-fetch
    kind: job
    image: mlrun/mlrun
    handler: data_fetch
  - url: ./src/train.py
    name: train
    kind: job
    image: mlrun/mlrun
    handler: train
  - url: ./src/serving.yaml
    name: serving
  workflows:
  - path: ./src/workflow.py
    name: main
  artifacts:
  - kind: model
    metadata:
      project: new-git-proj
      key: model-test
    spec:
      target_path: v3io:///projects/new-git-proj/artifacts/train-train/0/model/
      model_file: model.pkl
    status:
      state: created
  conda: ''
  source: git://github.com/GiladShapira94/load-project-example.git
  origin_url: git://github.com/GiladShapira94/load-project-example.git#refs/heads/master
  load_source_on_run: true
  desired_state: online
  owner: shapira
status:
  state: online
